wandb_version: 1

_wandb:
  desc: null
  value:
    python_version: 3.8.10
    cli_version: 0.15.8
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1692928844.560418
    t:
      1:
      - 1
      - 55
      2:
      - 1
      - 55
      3:
      - 15
      - 23
      4: 3.8.10
      5: 0.15.8
      8:
      - 5
